### ISSUE TITLE
Globi bei TWINT

### ISSUE THREAD

**Issue by shiftux** [Globi-der-Hacker/Twint-API#1]
Hi Globi

Interessantes Repo und super Readme!

Ich leite die Entwicklung bei TWINT und suche immer kompetente und interessierte Leute :)

Melde dich, wenn du gerne mal sprechen möchtest.

LG

**Comment by Globi-der-Hacker** [comment]
Super, dann kannst du sicher ein paar Pull-Requests beisteuern!
